#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

eval "$(conda shell.bash hook)"
export LD_PRELOAD="${CONDA_PREFIX}/lib/libgomp.so.1"

export OMP_NUM_THREADS=16
export MKL_NUM_THREADS=16
export OPENBLAS_NUM_THREADS=16

conda activate mace_env

cd "$REPO_ROOT"

mlip-ft mace \
  --curate-neb \
  --inputs "demo/fine_tuning/mace/0_raw_inputs/siv_rules.yml"
